services:
  # HTTP Backend Service
  - type: web
    name: drawnote-http-api
    env: node
    buildCommand: npm install -g yarn && yarn install --cache-folder /tmp/yarn-cache && cd packages/db && npx prisma generate && cd ../.. && npx turbo run build --filter=http-backend...
    startCommand: cd apps/http-backend && npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  # WebSocket Backend Service
  - type: web
    name: drawnote-ws-api
    env: node
    buildCommand: npm install -g yarn && yarn install --cache-folder /tmp/yarn-cache && cd packages/db && npx prisma generate && cd ../.. && npx turbo run build --filter=ws-backend...
    startCommand: cd apps/ws-backend && npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
